[toolchain]
channel = "nightly" # or "nightly-YYYY-MM-DD" for a specific date
profile = "default"
components = [ "rust-src", "llvm-tools-preview", "rustfmt", "rust-analyzer-preview"]
#components = [ "rust-src", "llvm-tools-preview", "rustfmt"]
targets = [
  "thumbv7em-none-eabihf", "thumbv6m-none-eabi"
]
